/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/update_checker.py:160: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  diff = datetime.utcnow() - the_datetime
/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/update_checker.py:160: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  diff = datetime.utcnow() - the_datetime
/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/update_checker.py:160: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  diff = datetime.utcnow() - the_datetime
Version 0.9.8 of metric_visualizer is outdated. Version 0.9.13 was released Wednesday May 01, 2024.
Traceback (most recent call last):
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 296, in <module>
Version 0.9.8 of metric_visualizer is outdated. Version 0.9.13 was released Wednesday May 01, 2024.
Traceback (most recent call last):
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 296, in <module>
    refresh()
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 287, in refresh
    refresh()
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 287, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/cmd.py", line 631, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/cmd.py", line 631, in refresh
Version 0.9.8 of metric_visualizer is outdated. Version 0.9.13 was released Wednesday May 01, 2024.
Traceback (most recent call last):
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 296, in <module>
    refresh()
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 287, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/s28zabed/opinionconv-refactor/ABSA.py", line 7, in <module>
    from pyabsa import AspectTermExtraction as ATEPC, DeviceTypeOption
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/__init__.py", line 13, in <module>
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/s28zabed/opinionconv-refactor/ABSA.py", line 7, in <module>
    if not Git.refresh(path=path):
    from pyabsa import AspectTermExtraction as ATEPC, DeviceTypeOption
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/__init__.py", line 13, in <module>
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/cmd.py", line 631, in refresh
    from pyabsa.utils.notification_utils.notification_utils import (
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/__init__.py", line 9, in <module>
    from pyabsa.utils.notification_utils.notification_utils import (
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/__init__.py", line 9, in <module>
    from pyabsa.utils.absa_utils.make_absa_dataset import make_ABSA_dataset
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/absa_utils/make_absa_dataset.py", line 15, in <module>
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/s28zabed/opinionconv-refactor/ABSA.py", line 7, in <module>
    from pyabsa.utils.absa_utils.make_absa_dataset import make_ABSA_dataset
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/absa_utils/make_absa_dataset.py", line 15, in <module>
    from pyabsa import AspectTermExtraction as ATEPC, DeviceTypeOption
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/__init__.py", line 13, in <module>
    from pyabsa.tasks.AspectTermExtraction.prediction.aspect_extractor import (
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/tasks/AspectTermExtraction/__init__.py", line 11, in <module>
    from pyabsa.tasks.AspectTermExtraction.prediction.aspect_extractor import (
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/tasks/AspectTermExtraction/__init__.py", line 11, in <module>
    from pyabsa.utils.notification_utils.notification_utils import (
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/__init__.py", line 9, in <module>
    from .trainer.atepc_trainer import ATEPCTrainer
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/tasks/AspectTermExtraction/trainer/atepc_trainer.py", line 18, in <module>
    from pyabsa.utils.absa_utils.make_absa_dataset import make_ABSA_dataset
    from .trainer.atepc_trainer import ATEPCTrainer
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/tasks/AspectTermExtraction/trainer/atepc_trainer.py", line 18, in <module>
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/absa_utils/make_absa_dataset.py", line 15, in <module>
    from pyabsa.framework.trainer_class.trainer_template import Trainer
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/framework/trainer_class/trainer_template.py", line 31, in <module>
    from pyabsa.framework.trainer_class.trainer_template import Trainer
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/framework/trainer_class/trainer_template.py", line 31, in <module>
    from pyabsa.tasks.AspectTermExtraction.prediction.aspect_extractor import (
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/tasks/AspectTermExtraction/__init__.py", line 11, in <module>
    from .trainer.atepc_trainer import ATEPCTrainer
    from ...utils.data_utils.dataset_manager import detect_dataset
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/tasks/AspectTermExtraction/trainer/atepc_trainer.py", line 18, in <module>
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/data_utils/dataset_manager.py", line 15, in <module>
    from ...utils.data_utils.dataset_manager import detect_dataset
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/data_utils/dataset_manager.py", line 15, in <module>
    from pyabsa.framework.trainer_class.trainer_template import Trainer
    import git
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 298, in <module>
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/framework/trainer_class/trainer_template.py", line 31, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
    import git
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 298, in <module>
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

    from ...utils.data_utils.dataset_manager import detect_dataset
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/pyabsa/utils/data_utils/dataset_manager.py", line 15, in <module>
    import git
  File "/home/s28zabed/opinionconv-refactor/myenv/lib/python3.12/site-packages/git/__init__.py", line 298, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

